### ISSUE TITLE
SG13G2 Standard Cells

### ISSUE THREAD

**Issue by FaragElsayed2** [IHP-GmbH/IHP-Open-PDK#108] opened 2024-05-12 14:55 UTC
## SG13G2 Standard Cells

It seems that there might be connectivity issues with the cdl files in the cells below.

### 1.sg13g2_nand2b_2

**Layout**
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/91015308/2013142e-00d2-40f5-befd-2c91ca9a3398)

**Current Cdl**
```
.SUBCKT sg13g2_nand2b_2 A_N B VDD VSS Y
*.PININFO A_N:I B:I Y:O VDD:B VSS:B
MX0 Y A VDD VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
MX1 A A_N VDD VDD sg13_lv_pmos m=1 w=840.00n l=130.00n ng=1
MX3 Y B VDD VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
MX2 Y A net1 VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
MX4 A A_N VSS VSS sg13_lv_nmos m=1 w=550.00n l=130.00n ng=1
MX5 net1 B VSS VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
.ENDS
```

**Expected Cdl**

```
.SUBCKT sg13g2_nand2b_2 A_N B VDD VSS Y
*.PININFO A_N:I B:I Y:O VDD:B VSS:B
MX0 Y A VDD VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
MX1 A A_N VDD VDD sg13_lv_pmos m=1 w=840.00n l=130.00n ng=1
MX3 Y B VDD VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
MX2 Y B net1 VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
MX4 A A_N VSS VSS sg13_lv_nmos m=1 w=550.00n l=130.00n ng=1
MX5 net1 A VSS VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
.ENDS
```

**Changes**

- Flipping the gate connection between `MX2` and `MX5`.

===================================================================

### 2.sg13g2_nor2b_1

**Layout**
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/91015308/ab0e3b77-f0a0-4c2b-871a-6211531981c5)

**Current Cdl**
```
.SUBCKT sg13g2_nor2b_1 A B_N VDD VSS Y
*.PININFO A:I B_N:I Y:O VDD:B VSS:B
MN0 B B_N VSS VSS sg13_lv_nmos m=1 w=550.00n l=130.00n ng=1
MX0 Y A VSS VSS sg13_lv_nmos m=1 w=740.00n l=130.00n ng=1
MX3 Y B VSS VSS sg13_lv_nmos m=1 w=740.00n l=130.00n ng=1
MP0 B B_N VDD VDD sg13_lv_pmos m=1 w=840.00n l=130.00n ng=1
MX1 net1 A VDD VDD sg13_lv_pmos m=1 w=1.12e-06 l=130.00n ng=1
MX2 Y B net1 VDD sg13_lv_pmos m=1 w=1.12e-06 l=130.00n ng=1
.ENDS
```

**Expected Cdl**

```
.SUBCKT sg13g2_nor2b_1 A B_N VDD VSS Y
*.PININFO A:I B_N:I Y:O VDD:B VSS:B
MN0 B B_N VSS VSS sg13_lv_nmos m=1 w=550.00n l=130.00n ng=1
MX0 Y A VSS VSS sg13_lv_nmos m=1 w=740.00n l=130.00n ng=1
MX3 Y B VSS VSS sg13_lv_nmos m=1 w=740.00n l=130.00n ng=1
MP0 B B_N VDD VDD sg13_lv_pmos m=1 w=840.00n l=130.00n ng=1
MX1 net1 B VDD VDD sg13_lv_pmos m=1 w=1.12e-06 l=130.00n ng=1
MX2 Y A net1 VDD sg13_lv_pmos m=1 w=1.12e-06 l=130.00n ng=1
.ENDS
```

**Changes**

- Flipping the gate connection between `MX1` and `MX2`.

===================================================================

### 3.sg13g2_nor2b_2

**Layout**
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/91015308/485d0fba-07fa-427d-a973-86389e2fe706)

**Current Cdl**
```
.SUBCKT sg13g2_nor2b_2 A B_N VDD VSS Y
*.PININFO A:I B_N:I Y:O VDD:B VSS:B
MN0 B B_N VSS VSS sg13_lv_nmos m=1 w=640.00n l=130.00n ng=1
MX0 Y A VSS VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
MX3 Y B VSS VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
MP0 B B_N VDD VDD sg13_lv_pmos m=1 w=1.000u l=130.00n ng=1
MX1 net1 A VDD VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
MX2 Y B net1 VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
.ENDS
```

**Expected Cdl**

```
.SUBCKT sg13g2_nor2b_2 A B_N VDD VSS Y
*.PININFO A:I B_N:I Y:O VDD:B VSS:B
MN0 B B_N VSS VSS sg13_lv_nmos m=1 w=640.00n l=130.00n ng=1
MX0 Y A VSS VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
MX3 Y B VSS VSS sg13_lv_nmos m=2 w=720.00n l=130.00n ng=1
MP0 B B_N VDD VDD sg13_lv_pmos m=1 w=1.000u l=130.00n ng=1
MX1 net1 B VDD VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
MX2 Y A net1 VDD sg13_lv_pmos m=2 w=1.12u l=130.00n ng=1
.ENDS
```

**Changes**

- Flipping the gate connection between `MX1` and `MX2`.

**Comment by sergeiandreyev** [comment] 2024-05-13 08:56
Hello @FaragElsayed2, it seems that there is an issue how KLayout LVS deck is recognizing the nets in these cells. I just checked the first one `nand2b_2`, we don't see violations using commercial tools, also if looking at KLayout LVS run:
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/116548619/3eae5705-9024-4590-a878-72ff7e2bc578)
The highlighted net is internal `A` net, but here is recognized as `B` in the netlist.
On the below screenshot the net `B` is incorrectly recognized as `A`:
![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/116548619/17c8df2e-3a78-472a-a56c-17d7c0d1738f)
We can have a call if you need

**Comment by atorkmabrains** [comment] 2024-05-13 13:18
@sergeiandreyev I believe we need to review this over a meeting. LVS seems to work correctly from my end.

**Comment by sergeiandreyev** [comment] 2024-05-15 12:20
Hi @FaragElsayed2 , could you please check on your side that the issue is fixed - then I'll close this item as resolved.

**Comment by FaragElsayed2** [comment] 2024-05-15 14:00
@sergeiandreyev, yes, it's fixed now. Thanks!

**Closed** 2024-05-15 14:00 UTC
Labels: bug
