### ISSUE TITLE
Glitch in capacitance evaluation

### ISSUE THREAD

**Issue by dwarning** [IHP-GmbH/IHP-Open-PDK#64] opened 2024-04-04 06:35 UTC
The attached ngspice script [cg_glitch.txt](https://github.com/IHP-GmbH/IHP-Open-PDK/files/14862148/cg_glitch.txt)  shows Cgb, Cg_ds and Cg_dsb capacitances over Vg of a 400/0.5 lv_nmos transistor.
The strong glitch around -0.9V is in my opinion fatal and follows in time step problems for transient simulation.

The observed behaviour is for psp103 version 6.0 and actual version 8.2 [va-models](https://github.com/dwarning/VA-Models/tree/main/code/psp103/vacode) and can also be seen for the hv-nmos device.

Would be fine to see same curves from same va-code with other simulators.

![cg_glitch](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/18441932/7cddc004-2ec7-4b02-839b-2c13cbb0fdef)

Additional open question is the y-axis scale of the documented curves in [report_nmos_lv](https://github.com/IHP-GmbH/IHP-Open-PDK/blob/main/ihp-sg13g2/libs.doc/meas/MOS/doc/report_nmos_lv.pdf) page 401. Are this 400 pF? Because e-12 is shown.

**Comment by sergeiandreyev** [comment] 2024-04-10 10:44
Hi @dwarning,
we still have to reproduce the testcase in Xyce, as well as run/recheck this for commercial (internal) PDK models
on your second question - yes, these are 400pF

**Comment by dwarning** [comment] 2024-04-10 21:13
I see no problem with adms/Xyce:

![Xyce](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/18441932/bced1c37-04a2-4efc-8499-09be13acafc9)

**Comment by KrzysztofHerman** [comment] 2024-04-12 10:45
Hello, @dwarning 
could you please share the testcase for Xyce as well, there is an inconsistency with the values on Y-axis.
As for the plots of `Cgdsb` I attach simulation results where `ng` parameter is used 

![image](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/141824113/fff1bc00-a9e5-4933-8ea2-ea998807f034)

the orange curve corresponds to the device with `ng=1`
`X1 _net2  _net0  _net2  _net2 sg13_lv_nmos w=400u l=0.5u`
and the blue one corresponds to the device with `ng=40` what limits `W` to `10u`
`X1 _net2  _net0  _net2  _net2 sg13_lv_nmos w=400u l=0.5u ng=40`

**Comment by dwarning** [comment] 2024-04-12 17:02
OK, scripts attached. ( spend not the time to adapt Xyce library syntax )
[cg_glitch.plt.txt](https://github.com/IHP-GmbH/IHP-Open-PDK/files/14961403/cg_glitch.plt.txt)
[cg_glitch.cir.txt](https://github.com/IHP-GmbH/IHP-Open-PDK/files/14961404/cg_glitch.cir.txt)
[cg_glitch.sp.txt](https://github.com/IHP-GmbH/IHP-Open-PDK/files/14961405/cg_glitch.sp.txt)

Even I assume that original problem has nothing to do with geometry control I used your recommended size:
`X1 _net2  _net0  _net2  _net2 sg13_lv_nmos w=400u l=0.5u ng=40`

adms - Xyce:
![adms_Xyce](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/18441932/06781579-a876-477c-bcd1-9e17264d73b5)

openvaf - ngspice:
![openvaf_ngspice](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/18441932/33b01131-6d08-403c-bef0-2da5ea10d194)

Because the glitch is at VFB I am sure there is a bug in the openvaf compilation. Not easy to find, but possible.

**Comment by sergeiandreyev** [comment] 2024-04-15 08:30
@metroid120, could you please take a look?..

**Comment by metroid120** [comment] 2024-04-15 09:30
What I can already say, is that the bug is related to NQS effects in "PSP103_ChargesNQS.include". 
It could indeed be an OpenVAF bug, but I did not yet find the exact cause.

**Comment by metroid120** [comment] 2024-04-15 11:30
I agree that this is a serious bug. I was not able to track the issue down exactnly, but I found that 
the issue is related to the PSP current calculation in "PSP103_SPCalculation.incldue"

```
// Core PSP current calculation
    Vdsat_lim    =  3.912023005 * phit1;
    if (xg <= 0.0) begin
        qis          =  0.0;
        xgm          =  xg - x_s;
        Voxm         =  xgm * phit1;
        qeff1        =  Voxm;
        Vdsat        =  Vdsat_lim;
        Vdse         =  Vds;
    end else begin // (xg > 0)
        ...
```
For the xg>0 branch, the variabel "Vxm" should be continued smoothly, but is not. 
I do not know exactly how those model functions should work together, so it is difficult to find the root cause.
Maybe somebody else has more insight...

**Comment by sergeiandreyev** [comment] 2024-04-18 17:34
It's good that this will be tracked on OpenVAF repo, but still I propose to have this issue open here until the fix in OpenVAF will be made available.

**Comment by metroid120** [comment] 2024-04-20 19:24
Thanks to the bad weather I spend some time on this. **Folks, can you please confirm.** 

If one replaces the following three code lines in the Verilog-A

```
            SP_S_delta0 = exp(SP_S_x0); \
            SP_S_delta1 = 1.0 / SP_S_delta0; \
```
(occurs 2 times in the code)

```
            delta_1s     =  exp(x_s); \
            Es           =  1.0 / delta_1s; \
```
with 
```
            SP_S_delta0 = exp(SP_S_x0); \
            SP_S_delta1 = exp(-SP_S_x0); \
```
```
            delta_1s     =  exp(x_s); \
            Es           =  exp(-x_s); \
```
(so in total 3 occurrences), the problem is gone.

**Comment by dwarning** [comment] 2024-04-20 21:57
I can agree - this 3 modifications let the glitch disappear. Seems openvaf makes a kind of over-optimization.

**Comment by metroid120** [comment] 2024-04-21 10:15
Ok @sergeiandreyev , then I guess we have a fix/workaround. Replace the blocks of code as described above and the Glitch is gone.

I think OpenVAF generates the derivative of $y2$ in the following structure 
$y1=exp(a)$
$y2=1/exp(a)$

as

$\frac{dy2}{dx}=-(exp(a))^{-2}\frac{da}{dx}$

which causes numerical problems in contrast to the mathematically equivalent

$\frac{dy2}{dx}=-exp(-a)\frac{da}{dx}$

but this is just my guess.

Anyhow I doubt that the fundamental OpenVAF issue will be fixed soon, since the project is not active.

**Comment by sergeiandreyev** [comment] 2024-04-22 11:56
@metroid120 , thank you for taking the time to thoroughly investigate this issue over the weekend and finding a solution!

**Closed** 2024-04-23 07:38 UTC
Labels: bug

**Comment by dwarning** [comment] 2024-04-23 08:35
A note that the modified PSP model from this distribution is to use would be preferable.
